# Generated by Django 5.0.7 on 2024-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
